export interface Env {
  AUTH_DB: D1Database;

  KROSA_MAJA_BASE_URL: string;
  KROSA_MAJA_SECRET: string;
  KROSA_MAJA_INTERNAL_ADMIN_SECRET: string;

  KROSA_MAJA_GITHUB_CLIENT_ID: string;
  KROSA_MAJA_GITHUB_CLIENT_SECRET: string;
  KROSA_MAJA_ALLOWED_GITHUB_IDS: string;
  KROSA_MAJA_ADMIN_GITHUB_IDS: string;

  KROSA_MAJA_CLOUDFLARE_CLIENT_ID?: string;
  KROSA_MAJA_CLOUDFLARE_CLIENT_SECRET?: string;
  KROSA_MAJA_CLOUDFLARE_SCOPES?: string;
}
